### ISSUE TITLE
dashbord不显示

### ISSUE THREAD

**Issue by ssrsec** [metaStor/SpringScan#4]
插件显示存在，但是dashbord不显示

**Comment by metaStor** [comment]
这个要等前面的dnslog扫描完才会添加到target里面，后面会缩短dnslog回连等待的时间

**Comment by metaStor** [comment]
> 插件显示存在，但是dashbord不显示


这个要等前面的dnslog扫描完才会添加到target里面，后续会改变缩短dnslog回连等待的时间

**Comment by ssrsec** [comment]
> > 插件显示存在，但是dashbord不显示
> 
> 这个要等前面的dnslog扫描完才会添加到target里面，后续会改变缩短dnslog回连等待的时间

确实，有几个等几小时了还没回连（中间有断网）

**Comment by metaStor** [comment]
> > > 插件显示存在，但是dashbord不显示
> > 
> > 
> > 这个要等前面的dnslog扫描完才会添加到target里面，后续会改变缩短dnslog回连等待的时间
> 
> 确实，有几个等几小时了还没回连（中间有断网）

确实dnslog的回连有问题，已更改和发布新release，大佬再试试

**Comment by ssrsec** [comment]
666
